# Generated by Django 2.2.8 on 2021-01-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArkademyStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=20)),
                ('keterangan', models.CharField(max_length=100)),
                ('harga', models.IntegerField()),
                ('jumlah', models.IntegerField()),
            ],
            options={
                'db_table': 'arkademystore',
            },
        ),
    ]
